name: Build Kubernox Stable Release
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  tag: '$(Build.BuildId)'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
    
- task: Docker@2
  displayName: Build an Kubernox Service Image
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kubernox/service'
    command: 'buildAndPush'
    Dockerfile: 'src/Kubernox.Service/Dockerfile'
    buildContext: '.'
    tags: |
      $(tag)
      latest

- task: Docker@2
  displayName: Build an Kubernox Datacenter Worker Image
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kubernox/kubernox-datacenter-worker'
    command: 'buildAndPush'
    Dockerfile: 'src/Kubernox.Workers/Dockerfile'
    buildContext: '.'
    tags: |
      $(tag)
      latest