version: '3.3'

services:
  kubernox_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: kubernoxPassword@0123
    volumes:
      - db_data:/var/lib/postgresql/data

  kubernox_rabbitmq:
    image: rabbitmq:3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: kubernoxUser@0123
      RABBITMQ_DEFAULT_PASS: kubernoxPassword@0123

  kubernox_redis:       
    image: redis
    restart: always
    command: redis-server --requirepass kubernoxPassword@0123

  kubernox_traefik:
    image: traefik:v2.4 
    restart: always
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
      - "6443:6443"
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml

  kubernox_ui:
    image: hello-world
    restart: always

  kubernox_services:
    image: hello-world
    restart: always

  kubernox_monitoring_worker:
    image: hello-world
    restart: always

  kubernox_datacenter_worker:
    image: hello-world
    restart: always

volumes:
    db_data: {}      