name: kubernox
namespace: kubernox
network: kubernox_network
extensions:
- name: zipkin
- name: seq
  logPath: ./.logs

services:
- name: db
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
  - name: ACCEPT_EULA
    value: "Y"
  - name: MSSQL_SA_PASSWORD
    value: Kubernox@0123
  - name: MSSQL_SA_USER
    value: sa
  bindings:
  - port: 14330
    containerPort: 1433
    name: dbBinding
    connectionString: Data Source=${host},${port};Initial Catalog=KUBERNOX;User Id=${env:MSSQL_SA_USER};Password=${env:MSSQL_SA_PASSWORD}
  volumes:
    - source: ./mssql/data
      target: /var/opt/mssql/data
    - source: ./mssql/log
      target: /var/opt/mssql/log
    - source: ./mssql/secrets
      target: /var/opt/mssql/secrets

- name: kubernox-service
  project: src/Kubernox.API/Kubernox.API.csproj
  replicas: 1
  bindings:
  - port: 5001
    protocol: https
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development

# ingress:
#   - name: ingress
#     bindings:
#       - port: 80
#         protocol: http
#         name: http-redirect
#       - port: 443
#         protocol: https
#         name: https-redirect
#     rules:
#       - path: /api
#         service: kubernox-service
#       - path: /logs
#         service: kubernox-service
#       - path: /ws
#         service: kubernox-service