name: kubernox
namespace: kubernox
network: kubernox_network
extensions:
- name: zipkin
- name: seq
  logPath: ./.logs

services:
- name: db
  image: postgres
  env:
  - name: POSTGRES_PASSWORD
    value: kubernoxDbPassword@0123
  - name: POSTGRES_USER
    value: kubernox
  bindings:
  - port: 5432 
  tags:
    - db
  volumes:
    - source: ./postgres-data
      target: /var/lib/postgresql/data

- name: kubernox-service
  project: src/Kubernox.Service/Kubernox.Service.csproj
  replicas: 1
  bindings:
  - port: 4001
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ConnectionStrings__Default
    value: Host=localhost;Database=kubernox;Username=kubernox;Password=kubernoxDbPassword@0123
  tags:
    - app

# - name: kubernox-host
#   project: src/Kubernox.Host/Kubernox.Host.csproj
#   replicas: 1
#   bindings:
#   - port: 4000
#   tags:
#     - app

- name: kubernox-workers
  project: src/Kubernox.Workers/Kubernox.Workers.csproj
  replicas: 1
  tags:
    - app 
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ConnectionStrings__Default
    value: Host=localhost;Database=kubernox;Username=kubernox;Password=kubernoxDbPassword@0123

ingress:
  - name: ingress
    bindings:
      - port: 80
        protocol: http
        name: http-redirect
      - port: 443
        protocol: https
        name: https-redirect
    rules:
      - path: /api
        service: kubernox-service
      - path: /logs
        service: kubernox-service
      - path: /ws
        service: kubernox-service
      # - path: /
      #   service: kubernox-host
