CREATE TABLE [Host]
(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Name] NVARCHAR(128) NOT NULL,
	[Token] NVARCHAR(250) NOT NULL,
	[User] NVARCHAR(250) NOT NULL,
	[Ip] NVARCHAR(250) NOT NULL,
	[CreateAt] DATETIME NOT NULL DEFAULT(GETUTCDATE())
);
