log:
  level: DEBUG

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
  insecure: true

providers:
  redis:
    endpoints:
      - "127.0.0.1:6379"  
    rootKey: "traefik"
    password: "kubernoxRedisPassword@0123"
  file:
    directory: "/traefik-conf"

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ":443"
  k3s:
    address: ":6443"

pilot:
    token: "679a4346-6f15-445c-a697-79a692971bff"

certificatesResolvers:
  certificatesresolvers:
    acme:
      tlsChallenge: {}
      email: grasseelsp@hotmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: "websecure"

  gandiResolver:
    acme:
      tlsChallenge: {}
      email: grasseelsp@hotmail.com
      storage: acme.json
      dnsChallenge:
        provider: gandiv5
        delayBeforeCheck: 30

  ovhResolver:
    acme:
      tlsChallenge: {}
      email: grasseelsp@hotmail.com
      storage: acme.json
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 30